// GENERATED by scripts/generate-ui-gallery.py from manifest.yaml — do not edit.
// Regenerate after editing manifest.yaml or after screenshot refreshes change
// the hashed reference filenames that the manifest's globs resolve to.
window.UI_GALLERY = {
 "platformCycle": [
  "android",
  "ios"
 ],
 "platformLabels": {
  "android": "Android",
  "ios": "iOS",
  "wear": "Wear OS"
 },
 "themes": [
  "light",
  "dark"
 ],
 "sections": [
  {
   "title": "Screens",
   "rows": [
    {
     "id": "home",
     "title": "Home",
     "axis": "State",
     "note": null,
     "height": 420,
     "variants": [
      {
       "id": "closed",
       "label": "Closed"
      },
      {
       "id": "open",
       "label": "Open"
      },
      {
       "id": "confirming",
       "label": "Confirming"
      },
      {
       "id": "sending",
       "label": "Sending"
      },
      {
       "id": "warning",
       "label": "Open too long"
      },
      {
       "id": "stale",
       "label": "Stale data"
      },
      {
       "id": "alerts",
       "label": "Alerts"
      },
      {
       "id": "signed-out",
       "label": "Signed out"
      }
     ],
     "items": [
      {
       "id": "screen",
       "label": "Phone",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "closed|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentClosedSignedInPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "closed|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentClosedSignedInPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "closed|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Home-closed-signed-out.1.png",
         "w": 1125,
         "h": 2436
        },
        "open|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentOpenSignedInPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "open|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentOpenSignedInPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "open|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Home-open-signed-in.1.png",
         "w": 1125,
         "h": 2436
        },
        "confirming|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentAwaitingConfirmationPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "confirming|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentAwaitingConfirmationPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "confirming|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Home-confirm-state.1.png",
         "w": 1125,
         "h": 2436
        },
        "sending|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentSendingToDoorPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "sending|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentSendingToDoorPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "warning|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentOpeningTooLongPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "warning|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentOpeningTooLongPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "warning|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Home-opening-too-long-warning.1.png",
         "w": 1125,
         "h": 2436
        },
        "stale|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentStaleBannerPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "stale|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentStaleBannerPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "alerts|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentPermissionMissingPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "alerts|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentPermissionMissingPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "alerts|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Home-with-alerts.1.png",
         "w": 1125,
         "h": 2436
        },
        "signed-out|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentSignedOutPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "signed-out|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentSignedOutPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "signed-out|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Home-sign-in-row.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      }
     ]
    },
    {
     "id": "home-remote-pill",
     "title": "Home, remote pill states",
     "axis": "Pill state",
     "note": "Same Home screen flipped through the remote-button health pill states.",
     "height": 420,
     "variants": [
      {
       "id": "online",
       "label": "Online"
      },
      {
       "id": "offline",
       "label": "Offline"
      },
      {
       "id": "unauthorized",
       "label": "Unauthorized"
      },
      {
       "id": "unknown",
       "label": "Unknown"
      }
     ],
     "items": [
      {
       "id": "screen",
       "label": "Phone",
       "platforms": [
        "android"
       ],
       "images": {
        "online|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentRemotePillOnlinePreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "online|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentRemotePillOnlinePreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "offline|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentRemotePillOfflinePreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "offline|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentRemotePillOfflinePreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "unauthorized|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentRemotePillUnauthorizedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "unauthorized|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentRemotePillUnauthorizedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "unknown|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentRemotePillUnknownPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "unknown|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentRemotePillUnknownPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        }
       }
      }
     ]
    },
    {
     "id": "history",
     "title": "History",
     "axis": "State",
     "note": null,
     "height": 420,
     "variants": [
      {
       "id": "recent",
       "label": "Recent events"
      },
      {
       "id": "closed-days",
       "label": "Closed days"
      },
      {
       "id": "empty",
       "label": "Empty"
      },
      {
       "id": "loading-older",
       "label": "Loading older"
      },
      {
       "id": "reached-beginning",
       "label": "Reached beginning"
      },
      {
       "id": "stale",
       "label": "Stale banner"
      }
     ],
     "items": [
      {
       "id": "screen",
       "label": "Phone",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "recent|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HistoryRedesignScreenshotTestKt/HistoryContentMultiDayPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "recent|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HistoryRedesignScreenshotTestKt/HistoryContentMultiDayPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "recent|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/History-recent-events.1.png",
         "w": 1125,
         "h": 2436
        },
        "closed-days|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HistoryRedesignScreenshotTestKt/HistoryContentMultiDayClosedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "closed-days|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HistoryRedesignScreenshotTestKt/HistoryContentMultiDayClosedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "closed-days|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/History-closed-states.1.png",
         "w": 1125,
         "h": 2436
        },
        "empty|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HistoryRedesignScreenshotTestKt/HistoryContentEmptyPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "empty|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HistoryRedesignScreenshotTestKt/HistoryContentEmptyPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "empty|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/History-empty.1.png",
         "w": 1125,
         "h": 2436
        },
        "loading-older|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/History-loading-older-page.1.png",
         "w": 1125,
         "h": 2436
        },
        "reached-beginning|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/History-reached-beginning.1.png",
         "w": 1125,
         "h": 2436
        },
        "stale|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/History-stale-banner.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      }
     ]
    },
    {
     "id": "settings",
     "title": "Settings",
     "axis": "State",
     "note": null,
     "height": 420,
     "variants": [
      {
       "id": "signed-in",
       "label": "Signed in (allowlisted)"
      },
      {
       "id": "signed-in-basic",
       "label": "Signed in (basic)"
      },
      {
       "id": "signed-out",
       "label": "Signed out"
      },
      {
       "id": "permission-denied",
       "label": "Notifications off"
      },
      {
       "id": "snooze-sending",
       "label": "Snooze sending"
      }
     ],
     "items": [
      {
       "id": "screen",
       "label": "Phone",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "signed-in|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SettingsContentSignedInAllowlistedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "signed-in|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SettingsContentSignedInAllowlistedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "signed-in|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Settings-signed-in-developer.1.png",
         "w": 1125,
         "h": 2436
        },
        "signed-in-basic|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SettingsContentSignedInBasicPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "signed-in-basic|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SettingsContentSignedInBasicPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "signed-out|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SettingsContentSignedOutPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "signed-out|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SettingsContentSignedOutPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "signed-out|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Settings-signed-out.1.png",
         "w": 1125,
         "h": 2436
        },
        "permission-denied|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SettingsContentPermissionDeniedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "permission-denied|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SettingsContentPermissionDeniedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "permission-denied|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Settings-notifications-disabled.1.png",
         "w": 1125,
         "h": 2436
        },
        "snooze-sending|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SettingsContentSnoozeInFlightPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "snooze-sending|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SettingsContentSnoozeInFlightPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "snooze-sending|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Settings-snooze-sending.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      }
     ]
    },
    {
     "id": "functions",
     "title": "Function list",
     "axis": "Access",
     "note": null,
     "height": 420,
     "variants": [
      {
       "id": "granted",
       "label": "Granted"
      },
      {
       "id": "denied",
       "label": "Denied"
      },
      {
       "id": "test-notifications",
       "label": "Test notifications"
      }
     ],
     "items": [
      {
       "id": "screen",
       "label": "Phone",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "granted|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/FunctionListContentPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "granted|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/FunctionListContentPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "granted|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Functions-granted.1.png",
         "w": 1125,
         "h": 2436
        },
        "denied|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/FunctionListContentDeniedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "denied|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/FunctionListContentDeniedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "denied|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Functions-locked.1.png",
         "w": 1125,
         "h": 2436
        },
        "test-notifications|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Functions-test-notifications.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      }
     ]
    },
    {
     "id": "diagnostics",
     "title": "Diagnostics",
     "axis": "State",
     "note": null,
     "height": 420,
     "variants": [
      {
       "id": "default",
       "label": "Counters"
      },
      {
       "id": "clearing",
       "label": "Clear in flight"
      }
     ],
     "items": [
      {
       "id": "screen",
       "label": "Phone",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/DiagnosticsContentPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/DiagnosticsContentPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        },
        "default|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Diagnostics-counters.1.png",
         "w": 1125,
         "h": 2436
        },
        "clearing|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/DiagnosticsContentClearInFlightPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "clearing|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/DiagnosticsContentClearInFlightPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        }
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Sheets & dialogs",
   "rows": [
    {
     "id": "sheet-snooze",
     "title": "Snooze sheet",
     "axis": "State",
     "note": null,
     "height": 300,
     "variants": [
      {
       "id": "off",
       "label": "Nothing selected"
      },
      {
       "id": "active",
       "label": "Option selected"
      }
     ],
     "items": [
      {
       "id": "sheet",
       "label": "Sheet",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "off|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SnoozeSheetContentOffPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 1519
        },
        "off|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SnoozeSheetContentOffPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 1519
        },
        "off|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Snooze-sheet-nothing-selected.1.png",
         "w": 1125,
         "h": 2436
        },
        "active|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SnoozeSheetContentActivePreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 1519
        },
        "active|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/SnoozeSheetContentActivePreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 1519
        },
        "active|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Snooze-sheet-option-selected.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      }
     ]
    },
    {
     "id": "sheet-account",
     "title": "Account & version sheets",
     "axis": null,
     "note": null,
     "height": 300,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "account",
       "label": "Account",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/AccountSheetContentSignedInPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 736
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/AccountSheetContentSignedInPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 736
        },
        "default|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Account-sheet.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      },
      {
       "id": "version",
       "label": "Version",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/VersionSheetContentPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 1255
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/VersionSheetContentPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 1255
        }
       }
      }
     ]
    },
    {
     "id": "info-sheets",
     "title": "Info sheets",
     "axis": null,
     "note": null,
     "height": 300,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "door-status",
       "label": "Door status",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/DoorStatusInfoSheetContentPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 634
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/DoorStatusInfoSheetContentPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 634
        },
        "default|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Info-door-status.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      },
      {
       "id": "remote-control",
       "label": "Remote control",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/RemoteControlInfoSheetContentPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 634
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/RemoteControlInfoSheetContentPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 634
        },
        "default|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Info-remote-control.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      }
     ]
    },
    {
     "id": "dialog-clear",
     "title": "Clear diagnostics dialog",
     "axis": null,
     "note": null,
     "height": 240,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "dialog",
       "label": "Dialog",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/ClearDiagnosticsDialogPreviewTest_Light_fc5b723e_0.png",
         "w": 840,
         "h": 758
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/SettingsRedesignScreenshotTestKt/ClearDiagnosticsDialogPreviewTest_Dark_77106447_0.png",
         "w": 840,
         "h": 758
        }
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Wide layouts (Android)",
   "rows": [
    {
     "id": "dashboard-widths",
     "title": "Home dashboard by width",
     "axis": null,
     "note": null,
     "height": 280,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "tablet-home",
       "label": "Home on tablet",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentOnTabletPreviewTest_Tablet Light_948f5cf6_0.png",
         "w": 2363,
         "h": 2888
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/HomeRedesignScreenshotTestKt/HomeContentOnTabletPreviewTest_Tablet Dark_e3fcbfbf_0.png",
         "w": 2363,
         "h": 2888
        }
       }
      },
      {
       "id": "w600",
       "label": "600 dp",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardPreview600dpTest_Light_1446eff4_0.png",
         "w": 1575,
         "h": 2100
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardPreview600dpTest_Dark_0cb0e3cd_0.png",
         "w": 1575,
         "h": 2100
        }
       }
      },
      {
       "id": "w840",
       "label": "840 dp",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardPreview840dpTest_Light_a433c26f_0.png",
         "w": 2205,
         "h": 2100
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardPreview840dpTest_Dark_85b5ce5b_0.png",
         "w": 2205,
         "h": 2100
        }
       }
      },
      {
       "id": "w1024",
       "label": "1024 dp",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardPreview1024dpTest_Light_35b0f031_0.png",
         "w": 2688,
         "h": 2100
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardPreview1024dpTest_Dark_884c341e_0.png",
         "w": 2688,
         "h": 2100
        }
       }
      },
      {
       "id": "w1280",
       "label": "1280 dp",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardPreview1280dpTest_Light_6d0a28d0_0.png",
         "w": 3360,
         "h": 2100
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardPreview1280dpTest_Dark_a134fc9d_0.png",
         "w": 3360,
         "h": 2100
        }
       }
      }
     ]
    },
    {
     "id": "rail",
     "title": "Navigation rail",
     "axis": null,
     "note": null,
     "height": 280,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "home-700",
       "label": "Home + rail (700 dp)",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeRailPreview700dpTest_Light_47d9098a_0.png",
         "w": 1838,
         "h": 2100
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeRailPreview700dpTest_Dark_aacdb9c5_0.png",
         "w": 1838,
         "h": 2100
        }
       }
      },
      {
       "id": "dash-700",
       "label": "Dashboard + rail (700 dp)",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardRailPreview700dpTest_Light_47d9098a_0.png",
         "w": 1838,
         "h": 2100
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardRailPreview700dpTest_Dark_aacdb9c5_0.png",
         "w": 1838,
         "h": 2100
        }
       }
      },
      {
       "id": "dash-916",
       "label": "Dashboard + rail (916 dp)",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardRailPreview916dpTest_Light_9d6edbd9_0.png",
         "w": 2405,
         "h": 1079
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/HomeDashboardRailPreview916dpTest_Dark_98d1e6d2_0.png",
         "w": 2405,
         "h": 1079
        }
       }
      }
     ]
    },
    {
     "id": "three-pane",
     "title": "Three-pane dashboard",
     "axis": null,
     "note": null,
     "height": 280,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "phone-landscape",
       "label": "Phone landscape",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/ThreePaneDashboardPhoneLandscapePreviewTest_Light_9d6edbd9_0.png",
         "w": 2405,
         "h": 1079
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/ThreePaneDashboardPhoneLandscapePreviewTest_Dark_98d1e6d2_0.png",
         "w": 2405,
         "h": 1079
        }
       }
      },
      {
       "id": "tablet-narrow",
       "label": "Tablet narrow",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/ThreePaneDashboardTabletNarrowPreviewTest_Light_070fb0c3_0.png",
         "w": 2688,
         "h": 2016
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/ThreePaneDashboardTabletNarrowPreviewTest_Dark_ad262b53_0.png",
         "w": 2688,
         "h": 2016
        }
       }
      },
      {
       "id": "large-tablet",
       "label": "Large tablet",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/ThreePaneDashboardLargeTabletPreviewTest_Light_6d0a28d0_0.png",
         "w": 3360,
         "h": 2100
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/ThreePaneDashboardLargeTabletPreviewTest_Dark_a134fc9d_0.png",
         "w": 3360,
         "h": 2100
        }
       }
      },
      {
       "id": "diagnostics-overlay",
       "label": "Diagnostics overlay",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/ThreePaneDashboardWithDiagnosticsOverlayPreviewTest_Light_6d0a28d0_0.png",
         "w": 3360,
         "h": 2100
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ScreensScreenshotTestKt/ThreePaneDashboardWithDiagnosticsOverlayPreviewTest_Dark_a134fc9d_0.png",
         "w": 3360,
         "h": 2100
        }
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Door",
   "rows": [
    {
     "id": "door-canvas",
     "title": "Door canvas",
     "axis": null,
     "note": "The shared door drawing. iOS renders the same geometry from the KMP constants.",
     "height": 170,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "closed",
       "label": "Closed",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorClosedPreviewTest_Light_fc5b723e_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorClosedPreviewTest_Dark_77106447_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Door-closed.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      },
      {
       "id": "opening",
       "label": "Opening",
       "platforms": [
        "android",
        "ios"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorOpeningPreviewTest_Light_fc5b723e_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorOpeningPreviewTest_Dark_77106447_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Door-opening.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      },
      {
       "id": "midway",
       "label": "Midway",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorMidwayPreviewTest_Light_fc5b723e_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorMidwayPreviewTest_Dark_77106447_0.png",
         "w": 1050,
         "h": 1050
        }
       }
      },
      {
       "id": "open",
       "label": "Open",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorOpenPreviewTest_Light_fc5b723e_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorOpenPreviewTest_Dark_77106447_0.png",
         "w": 1050,
         "h": 1050
        }
       }
      },
      {
       "id": "closing",
       "label": "Closing",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorClosingPreviewTest_Light_fc5b723e_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorClosingPreviewTest_Dark_77106447_0.png",
         "w": 1050,
         "h": 1050
        }
       }
      },
      {
       "id": "opening-too-long",
       "label": "Opening too long",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorOpeningTooLongPreviewTest_Light_fc5b723e_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorOpeningTooLongPreviewTest_Dark_77106447_0.png",
         "w": 1050,
         "h": 1050
        }
       }
      },
      {
       "id": "closing-too-long",
       "label": "Closing too long",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorClosingTooLongPreviewTest_Light_fc5b723e_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorClosingTooLongPreviewTest_Dark_77106447_0.png",
         "w": 1050,
         "h": 1050
        }
       }
      },
      {
       "id": "sensor-conflict",
       "label": "Sensor conflict",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorErrorSensorConflictPreviewTest_Light_fc5b723e_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorErrorSensorConflictPreviewTest_Dark_77106447_0.png",
         "w": 1050,
         "h": 1050
        }
       }
      },
      {
       "id": "misaligned",
       "label": "Open misaligned",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorOpenMisalignedPreviewTest_Light_fc5b723e_0.png",
         "w": 1050,
         "h": 1050
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageDoorOpenMisalignedPreviewTest_Dark_77106447_0.png",
         "w": 1050,
         "h": 1050
        }
       }
      }
     ]
    },
    {
     "id": "door-grid-ios",
     "title": "Door states grid (iOS)",
     "axis": null,
     "note": "The iOS snapshot gallery captures all door states as one composite.",
     "height": 320,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "grid",
       "label": "All states",
       "platforms": [
        "ios"
       ],
       "images": {
        "default|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Door-states.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      }
     ]
    },
    {
     "id": "garage-icon",
     "title": "Garage icon",
     "axis": null,
     "note": null,
     "height": 120,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "icon",
       "label": "Icon",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageIconPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 1080
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/GarageDoorScreenshotTestKt/GarageIconPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 1080
        }
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Remote button",
   "rows": [
    {
     "id": "door-button",
     "title": "Garage door button",
     "axis": null,
     "note": "The round remote button, one tile per ButtonStateMachine state.",
     "height": 150,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "ready",
       "label": "Ready",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonReadyPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 168
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonReadyPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 168
        }
       }
      },
      {
       "id": "preparing",
       "label": "Preparing",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonPreparingPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 168
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonPreparingPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 168
        }
       }
      },
      {
       "id": "awaiting",
       "label": "Awaiting confirmation",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonAwaitingConfirmationPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 168
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonAwaitingConfirmationPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 168
        }
       }
      },
      {
       "id": "sending-server",
       "label": "Sending to server",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonSendingToServerPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 168
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonSendingToServerPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 168
        }
       }
      },
      {
       "id": "sending-door",
       "label": "Sending to door",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonSendingToDoorPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 168
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonSendingToDoorPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 168
        }
       }
      },
      {
       "id": "succeeded",
       "label": "Succeeded",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonSucceededPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 168
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonSucceededPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 168
        }
       }
      },
      {
       "id": "cancelled",
       "label": "Cancelled",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonCancelledPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 168
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonCancelledPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 168
        }
       }
      },
      {
       "id": "server-failed",
       "label": "Server failed",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonServerFailedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 168
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonServerFailedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 168
        }
       }
      },
      {
       "id": "door-failed",
       "label": "Door failed",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonDoorFailedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 168
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/GarageDoorButtonDoorFailedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 168
        }
       }
      }
     ]
    },
    {
     "id": "button-grid-ios",
     "title": "Remote button states grid (iOS)",
     "axis": null,
     "note": null,
     "height": 320,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "grid",
       "label": "All states",
       "platforms": [
        "ios"
       ],
       "images": {
        "default|ios|light": {
         "src": "../iosApp/SnapshotTests/__Snapshots__/PreviewTests.generated/Remote-button-states.1.png",
         "w": 1125,
         "h": 2436
        }
       }
      }
     ]
    },
    {
     "id": "remote-section",
     "title": "Remote control section",
     "axis": "Button state",
     "note": "The full-width Home section that hosts the button, flipped through states.",
     "height": 240,
     "variants": [
      {
       "id": "ready",
       "label": "Ready"
      },
      {
       "id": "preparing",
       "label": "Preparing"
      },
      {
       "id": "awaiting",
       "label": "Awaiting confirmation"
      },
      {
       "id": "sending-server",
       "label": "Sending to server"
      },
      {
       "id": "sending-door",
       "label": "Sending to door"
      },
      {
       "id": "succeeded",
       "label": "Succeeded"
      },
      {
       "id": "cancelled",
       "label": "Cancelled"
      },
      {
       "id": "server-failed",
       "label": "Server failed"
      },
      {
       "id": "door-failed",
       "label": "Door failed"
      }
     ],
     "items": [
      {
       "id": "section",
       "label": "Section",
       "platforms": [
        "android"
       ],
       "images": {
        "ready|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 295
        },
        "ready|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 295
        },
        "preparing|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentPreparingPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 295
        },
        "preparing|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentPreparingPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 295
        },
        "awaiting|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentAwaitingConfirmationPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 295
        },
        "awaiting|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentAwaitingConfirmationPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 295
        },
        "sending-server|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentSendingToServerPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 295
        },
        "sending-server|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentSendingToServerPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 295
        },
        "sending-door|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentSendingToDoorPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 295
        },
        "sending-door|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentSendingToDoorPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 295
        },
        "succeeded|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentSucceededPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 295
        },
        "succeeded|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentSucceededPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 295
        },
        "cancelled|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentCancelledPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 295
        },
        "cancelled|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentCancelledPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 295
        },
        "server-failed|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentServerFailedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 295
        },
        "server-failed|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentServerFailedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 295
        },
        "door-failed|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentDoorFailedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 295
        },
        "door-failed|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonContentDoorFailedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 295
        }
       }
      }
     ]
    },
    {
     "id": "network-diagram",
     "title": "Network diagram",
     "axis": null,
     "note": "The phone-to-server-to-door progress diagram shown while a press is in flight.",
     "height": 150,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "idle",
       "label": "Idle",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramIdlePreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 95
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramIdlePreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 95
        }
       }
      },
      {
       "id": "sending-server",
       "label": "Sending to server",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramSendingToServerPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 95
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramSendingToServerPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 95
        }
       }
      },
      {
       "id": "sending-door",
       "label": "Sending to door",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramSendingToDoorPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 95
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramSendingToDoorPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 95
        }
       }
      },
      {
       "id": "succeeded",
       "label": "Succeeded",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramSucceededPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 95
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramSucceededPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 95
        }
       }
      },
      {
       "id": "server-failed",
       "label": "Server failed",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramServerFailedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 95
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramServerFailedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 95
        }
       }
      },
      {
       "id": "door-failed",
       "label": "Door failed",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramDoorFailedPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 95
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/NetworkDiagramDoorFailedPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 95
        }
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Pills & cards",
   "rows": [
    {
     "id": "checkin-pill",
     "title": "Device check-in pill",
     "axis": null,
     "note": null,
     "height": 100,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "fresh",
       "label": "Fresh",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/DeviceCheckInPillFreshPreviewTest_Light_fc5b723e_0.png",
         "w": 238,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/DeviceCheckInPillFreshPreviewTest_Dark_77106447_0.png",
         "w": 238,
         "h": 45
        }
       }
      },
      {
       "id": "aging",
       "label": "Aging",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/DeviceCheckInPillAgingPreviewTest_Light_fc5b723e_0.png",
         "w": 323,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/DeviceCheckInPillAgingPreviewTest_Dark_77106447_0.png",
         "w": 323,
         "h": 45
        }
       }
      },
      {
       "id": "stale",
       "label": "Stale",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/DeviceCheckInPillStalePreviewTest_Light_fc5b723e_0.png",
         "w": 241,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/DeviceCheckInPillStalePreviewTest_Dark_77106447_0.png",
         "w": 241,
         "h": 45
        }
       }
      },
      {
       "id": "no-data",
       "label": "No data",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/DeviceCheckInPillNoDataPreviewTest_Light_fc5b723e_0.png",
         "w": 77,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/DeviceCheckInPillNoDataPreviewTest_Dark_77106447_0.png",
         "w": 77,
         "h": 45
        }
       }
      }
     ]
    },
    {
     "id": "health-pill",
     "title": "Remote button health pill",
     "axis": null,
     "note": null,
     "height": 100,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "available",
       "label": "Available",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonHealthPillAvailablePreviewTest_Light_fc5b723e_0.png",
         "w": 214,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonHealthPillAvailablePreviewTest_Dark_77106447_0.png",
         "w": 214,
         "h": 45
        }
       }
      },
      {
       "id": "unauthorized",
       "label": "Unauthorized",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonHealthPillUnauthorizedPreviewTest_Light_fc5b723e_0.png",
         "w": 271,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonHealthPillUnauthorizedPreviewTest_Dark_77106447_0.png",
         "w": 271,
         "h": 45
        }
       }
      },
      {
       "id": "unavailable",
       "label": "Unavailable",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonHealthPillUnavailablePreviewTest_Light_fc5b723e_0.png",
         "w": 425,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonHealthPillUnavailablePreviewTest_Dark_77106447_0.png",
         "w": 425,
         "h": 45
        }
       }
      },
      {
       "id": "unknown",
       "label": "Unknown",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonHealthPillUnknownPreviewTest_Light_fc5b723e_0.png",
         "w": 215,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteButtonHealthPillUnknownPreviewTest_Dark_77106447_0.png",
         "w": 215,
         "h": 45
        }
       }
      }
     ]
    },
    {
     "id": "offline-pill",
     "title": "Remote offline pill",
     "axis": null,
     "note": null,
     "height": 100,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "fresh",
       "label": "Fresh",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteOfflinePillFreshPreviewTest_Light_fc5b723e_0.png",
         "w": 408,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteOfflinePillFreshPreviewTest_Dark_77106447_0.png",
         "w": 408,
         "h": 45
        }
       }
      },
      {
       "id": "aging",
       "label": "Aging",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteOfflinePillAgingPreviewTest_Light_fc5b723e_0.png",
         "w": 425,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteOfflinePillAgingPreviewTest_Dark_77106447_0.png",
         "w": 425,
         "h": 45
        }
       }
      },
      {
       "id": "stale",
       "label": "Stale",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteOfflinePillStalePreviewTest_Light_fc5b723e_0.png",
         "w": 386,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteOfflinePillStalePreviewTest_Dark_77106447_0.png",
         "w": 386,
         "h": 45
        }
       }
      },
      {
       "id": "very-stale",
       "label": "Very stale",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteOfflinePillVeryStalePreviewTest_Light_fc5b723e_0.png",
         "w": 421,
         "h": 45
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/RemoteOfflinePillVeryStalePreviewTest_Dark_77106447_0.png",
         "w": 421,
         "h": 45
        }
       }
      }
     ]
    },
    {
     "id": "status-card",
     "title": "Door status card",
     "axis": null,
     "note": null,
     "height": 190,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "card",
       "label": "Card",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/DoorStatusCardPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 2400
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/DoorStatusCardPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 2400
        }
       }
      }
     ]
    },
    {
     "id": "error-card",
     "title": "Error card",
     "axis": null,
     "note": null,
     "height": 190,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "default",
       "label": "Default",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/ErrorCardPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 210
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/ErrorCardPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 210
        }
       }
      },
      {
       "id": "long-word",
       "label": "Long button word",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/ErrorCardLongButtonWordPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 651
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/ErrorCardLongButtonWordPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 651
        }
       }
      },
      {
       "id": "many-words",
       "label": "Many button words",
       "platforms": [
        "android"
       ],
       "images": {
        "default|android|light": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/ErrorCardManyButtonWordsPreviewTest_Light_fc5b723e_0.png",
         "w": 1080,
         "h": 550
        },
        "default|android|dark": {
         "src": "../android-screenshot-tests/src/screenshotTestDebug/reference/com/chriscartland/garage/screenshottests/ComponentsScreenshotTestKt/ErrorCardManyButtonWordsPreviewTest_Dark_77106447_0.png",
         "w": 1080,
         "h": 550
        }
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Wear OS",
   "rows": [
    {
     "id": "wear-hero",
     "title": "Hero flow",
     "axis": null,
     "note": "The single wear screen through the press narrative. Emulator captures, clock pinned to 10:10.",
     "height": 220,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "closed",
       "label": "Closed",
       "platforms": [
        "wear"
       ],
       "images": {
        "default|wear|light": {
         "src": "../screenshots/store/wear/wear-closed.png",
         "w": 454,
         "h": 454
        },
        "default|wear|dark": {
         "src": "../screenshots/store/wear/wear-closed.png",
         "w": 454,
         "h": 454
        }
       }
      },
      {
       "id": "armed",
       "label": "Armed",
       "platforms": [
        "wear"
       ],
       "images": {
        "default|wear|light": {
         "src": "../screenshots/store/wear/wear-armed.png",
         "w": 454,
         "h": 454
        },
        "default|wear|dark": {
         "src": "../screenshots/store/wear/wear-armed.png",
         "w": 454,
         "h": 454
        }
       }
      },
      {
       "id": "holding",
       "label": "Holding",
       "platforms": [
        "wear"
       ],
       "images": {
        "default|wear|light": {
         "src": "../screenshots/store/wear/wear-holding.png",
         "w": 454,
         "h": 454
        },
        "default|wear|dark": {
         "src": "../screenshots/store/wear/wear-holding.png",
         "w": 454,
         "h": 454
        }
       }
      },
      {
       "id": "moving",
       "label": "Moving",
       "platforms": [
        "wear"
       ],
       "images": {
        "default|wear|light": {
         "src": "../screenshots/store/wear/wear-moving.png",
         "w": 454,
         "h": 454
        },
        "default|wear|dark": {
         "src": "../screenshots/store/wear/wear-moving.png",
         "w": 454,
         "h": 454
        }
       }
      },
      {
       "id": "open",
       "label": "Open",
       "platforms": [
        "wear"
       ],
       "images": {
        "default|wear|light": {
         "src": "../screenshots/store/wear/wear-open.png",
         "w": 454,
         "h": 454
        },
        "default|wear|dark": {
         "src": "../screenshots/store/wear/wear-open.png",
         "w": 454,
         "h": 454
        }
       }
      }
     ]
    },
    {
     "id": "wear-signin",
     "title": "Sign-in",
     "axis": null,
     "note": null,
     "height": 220,
     "variants": [
      {
       "id": "default",
       "label": "Default"
      }
     ],
     "items": [
      {
       "id": "signed-out",
       "label": "Signed out",
       "platforms": [
        "wear"
       ],
       "images": {
        "default|wear|light": {
         "src": "../screenshots/store/wear/wear-signed_out.png",
         "w": 454,
         "h": 454
        },
        "default|wear|dark": {
         "src": "../screenshots/store/wear/wear-signed_out.png",
         "w": 454,
         "h": 454
        }
       }
      },
      {
       "id": "sign-in-error",
       "label": "Sign-in error",
       "platforms": [
        "wear"
       ],
       "images": {
        "default|wear|light": {
         "src": "../screenshots/store/wear/wear-sign_in_error.png",
         "w": 454,
         "h": 454
        },
        "default|wear|dark": {
         "src": "../screenshots/store/wear/wear-sign_in_error.png",
         "w": 454,
         "h": 454
        }
       }
      }
     ]
    }
   ]
  }
 ]
};
