/*
 * Copyright 2026 Chris Cartland. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.chriscartland.garage.usecase

import com.chriscartland.garage.domain.model.VoiceIntent

/**
 * Gold-labeled eval corpus for voice-intent classifier engines,
 * generated by an adversarial multi-agent pass (2026-07-24): six
 * generator lenses produced candidate ASR transcripts, then two
 * independent judge agents labeled every case from scratch against the
 * policy in docs/VOICE_COMMANDS.md; a case is kept only with 2-of-3
 * label consensus (generator + judges), and judge consensus overrides
 * the generator. Notes are generator provenance and may predate a
 * judge override.
 *
 * Grow this list freely (real device transcripts are the best source);
 * labels follow the policy: intent only when THIS TEXT clearly requests
 * a direction; actionable only for explicit, unconditional,
 * present-tense imperatives.
 */
object VoiceEvalCorpus {
    val CASES: List<VoiceEvalCase> = listOf(
        // --- imperative ---
        VoiceEvalCase(
            "open the garage door",
            VoiceIntent.OPEN,
            true,
            "imperative",
            "Canonical explicit imperative, present tense, unconditional",
        ),
        VoiceEvalCase("close the garage door", VoiceIntent.CLOSE, true, "imperative", "Canonical explicit close imperative"),
        VoiceEvalCase(
            "please open the garage",
            VoiceIntent.OPEN,
            true,
            "imperative",
            "Politeness marker does not weaken the imperative; garage = the door",
        ),
        VoiceEvalCase("shut the garage door", VoiceIntent.CLOSE, true, "imperative", "Synonym shut is an explicit close request"),
        VoiceEvalCase(
            "open the door please",
            VoiceIntent.OPEN,
            true,
            "imperative",
            "Trailing politeness, still a direct command in a garage-door app context",
        ),
        VoiceEvalCase("close the door", VoiceIntent.CLOSE, true, "imperative", "Bare object variant door, explicit imperative"),
        VoiceEvalCase(
            "go ahead and open the garage door",
            VoiceIntent.OPEN,
            true,
            "imperative",
            "Filler preamble go ahead and, door clause explicit and unconditional",
        ),
        VoiceEvalCase(
            "shut the garage for me",
            VoiceIntent.CLOSE,
            true,
            "imperative",
            "For me is benign politeness; explicit close request",
        ),
        VoiceEvalCase(
            "open the garage door and turn on the lights",
            VoiceIntent.OPEN,
            true,
            "imperative",
            "Door clause itself explicit and unconditional; extra clause irrelevant",
        ),
        VoiceEvalCase(
            "garage door open now",
            VoiceIntent.UNKNOWN,
            false,
            "imperative",
            "Word-order variant still an unambiguous present-tense open command",
        ),
        VoiceEvalCase(
            "can you close the garage door",
            VoiceIntent.CLOSE,
            false,
            "imperative",
            "Permission-question form; intent clear but policy says not actionable",
        ),
        VoiceEvalCase(
            "close the garage when i pull out",
            VoiceIntent.CLOSE,
            false,
            "imperative",
            "Temporal deferral makes it conditional, not now",
        ),
        VoiceEvalCase("dont open the garage door", VoiceIntent.UNKNOWN, false, "imperative", "Negation; not a request for movement"),
        VoiceEvalCase(
            "i want the garage door open",
            VoiceIntent.OPEN,
            false,
            "imperative",
            "Desire statement, not an unconditional imperative",
        ),
        VoiceEvalCase(
            "open the garage a little bit",
            VoiceIntent.OPEN,
            true,
            "imperative",
            "Explicit present open command; qualifier a little bit does not add condition or negation",
        ),
        // --- question ---
        VoiceEvalCase(
            "can you open the garage door",
            VoiceIntent.OPEN,
            false,
            "question",
            "Permission/ability question, not an unconditional imperative",
        ),
        VoiceEvalCase(
            "could you close the garage door please",
            VoiceIntent.CLOSE,
            false,
            "question",
            "Polite ability phrasing is a question, not actionable",
        ),
        VoiceEvalCase(
            "would you mind opening the garage",
            VoiceIntent.OPEN,
            false,
            "question",
            "Would-you-mind hedge is a permission form",
        ),
        VoiceEvalCase("i want you to close the door", VoiceIntent.CLOSE, false, "question", "Desire phrasing, not an explicit imperative"),
        VoiceEvalCase(
            "is it possible to open the garage from here",
            VoiceIntent.UNKNOWN,
            false,
            "question",
            "Capability question about opening, not a request to act now",
        ),
        VoiceEvalCase(
            "why dont you close the garage door",
            VoiceIntent.CLOSE,
            false,
            "question",
            "Rhetorical suggestion form, hedged, not unconditional",
        ),
        VoiceEvalCase("can we get the garage closed", VoiceIntent.CLOSE, false, "question", "Ability question with indirect phrasing"),
        VoiceEvalCase("do you think you could open the door", VoiceIntent.OPEN, false, "question", "Doubly hedged ability question"),
        VoiceEvalCase(
            "would it be okay to close the garage now",
            VoiceIntent.CLOSE,
            false,
            "question",
            "Permission-seeking question, not a command",
        ),
        VoiceEvalCase(
            "id like the garage door closed",
            VoiceIntent.CLOSE,
            false,
            "question",
            "Preference statement (id like), not an imperative",
        ),
        VoiceEvalCase("any chance you can open the garage", VoiceIntent.OPEN, false, "question", "Hedged ability inquiry"),
        VoiceEvalCase(
            "maybe you could close the door",
            VoiceIntent.CLOSE,
            false,
            "question",
            "Maybe hedge makes it a suggestion, not unconditional",
        ),
        VoiceEvalCase(
            "is there a way to close the garage",
            VoiceIntent.CLOSE,
            false,
            "question",
            "Pure how-to/capability question; may be asking about the app, not requesting movement",
        ),
        VoiceEvalCase(
            "can it open by itself",
            VoiceIntent.UNKNOWN,
            false,
            "question",
            "Question about door capability, no clear movement request",
        ),
        // --- negation ---
        VoiceEvalCase(
            "dont open the door",
            VoiceIntent.UNKNOWN,
            false,
            "negation",
            "Negated command; requests NOT moving the door, no movement intent",
        ),
        VoiceEvalCase(
            "no wait dont close it",
            VoiceIntent.UNKNOWN,
            false,
            "negation",
            "Mid-utterance cancellation of a close; negation makes it a non-request",
        ),
        VoiceEvalCase("never mind", VoiceIntent.UNKNOWN, false, "negation", "Pure cancellation, no door direction at all"),
        VoiceEvalCase("stop", VoiceIntent.UNKNOWN, false, "negation", "Halt/cancel word; no direction requested"),
        VoiceEvalCase(
            "i said dont open it",
            VoiceIntent.UNKNOWN,
            false,
            "negation",
            "Emphatic negation restating a prohibition; not a movement request",
        ),
        VoiceEvalCase(
            "close the door no wait dont",
            VoiceIntent.UNKNOWN,
            false,
            "negation",
            "Command immediately retracted; final speaker intent is cancellation",
        ),
        VoiceEvalCase(
            "open the garage actually never mind",
            VoiceIntent.UNKNOWN,
            false,
            "negation",
            "Self-correction cancels the open request",
        ),
        VoiceEvalCase(
            "dont close the garage yet",
            VoiceIntent.UNKNOWN,
            false,
            "negation",
            "Negation plus temporal deferral; asks for no action now",
        ),
        VoiceEvalCase("cancel that", VoiceIntent.UNKNOWN, false, "negation", "Explicit cancellation of a prior command; no direction"),
        VoiceEvalCase("no dont", VoiceIntent.UNKNOWN, false, "negation", "Bare refusal; nothing to execute"),
        VoiceEvalCase(
            "whatever you do dont open that door",
            VoiceIntent.UNKNOWN,
            false,
            "negation",
            "Strong prohibition against opening; not a movement request",
        ),
        VoiceEvalCase(
            "stop dont close it on the car",
            VoiceIntent.UNKNOWN,
            false,
            "negation",
            "Urgent negation to prevent closing; safety-critical non-action",
        ),
        VoiceEvalCase(
            "i didnt say open the door",
            VoiceIntent.UNKNOWN,
            false,
            "negation",
            "Denial of a prior command; describes speech, requests nothing",
        ),
        VoiceEvalCase("wait stop the door", VoiceIntent.UNKNOWN, false, "negation", "Halt request during motion; no open/close direction"),
        VoiceEvalCase(
            "no not the garage door",
            VoiceIntent.UNKNOWN,
            false,
            "negation",
            "Correction rejecting the garage door as target; no movement requested",
        ),
        // --- asrnoise ---
        VoiceEvalCase(
            "clothes the garage door",
            VoiceIntent.UNKNOWN,
            false,
            "asrnoise",
            "Homophone mishearing of close; text as written is not a door-movement request",
        ),
        VoiceEvalCase(
            "shut the poor",
            VoiceIntent.UNKNOWN,
            false,
            "asrnoise",
            "Poor is a misheard object; no clear door request in the text",
        ),
        VoiceEvalCase(
            "open the store",
            VoiceIntent.UNKNOWN,
            false,
            "asrnoise",
            "Store likely misheard door, but text does not request door movement",
        ),
        VoiceEvalCase(
            "open door",
            VoiceIntent.OPEN,
            true,
            "asrnoise",
            "Dropped article; intent clear but truncated transcript warrants confirmation not action",
        ),
        VoiceEvalCase("the door", VoiceIntent.UNKNOWN, false, "asrnoise", "Verb dropped by ASR; no direction expressed"),
        VoiceEvalCase("close the garage store", VoiceIntent.UNKNOWN, false, "asrnoise", "Misheard object noun; not clearly the door"),
        VoiceEvalCase(
            "please close the garage door",
            VoiceIntent.CLOSE,
            true,
            "asrnoise",
            "Explicit present-tense unconditional close command",
        ),
        VoiceEvalCase(
            "opened the garage door",
            VoiceIntent.UNKNOWN,
            false,
            "asrnoise",
            "Past tense from ASR; reads as state description not a command",
        ),
        VoiceEvalCase("open the garage stir", VoiceIntent.UNKNOWN, false, "asrnoise", "Split/misheard word; object unclear"),
        VoiceEvalCase(
            "close the door e",
            VoiceIntent.CLOSE,
            false,
            "asrnoise",
            "Trailing ASR fragment after clear command; junk token means possible truncation so hold action",
        ),
        VoiceEvalCase(
            "okay google open the garage door",
            VoiceIntent.OPEN,
            true,
            "asrnoise",
            "Wake word captured in transcript; door clause itself explicit and unconditional",
        ),
        VoiceEvalCase(
            "close the guard door",
            VoiceIntent.UNKNOWN,
            false,
            "asrnoise",
            "Guard is a mishearing of garage; object as written is not the garage door",
        ),
        VoiceEvalCase(
            "open the grudge door",
            VoiceIntent.UNKNOWN,
            false,
            "asrnoise",
            "Grudge misheard for garage; text does not clearly name the garage door",
        ),
        // --- smalltalk ---
        VoiceEvalCase("the garage door is open again", VoiceIntent.UNKNOWN, false, "smalltalk", "state description, not a request"),
        VoiceEvalCase("who left the garage door open", VoiceIntent.UNKNOWN, false, "smalltalk", "rhetorical question about past state"),
        VoiceEvalCase("i already closed the garage", VoiceIntent.UNKNOWN, false, "smalltalk", "past-tense report, no request"),
        VoiceEvalCase("that was a close call", VoiceIntent.UNKNOWN, false, "smalltalk", "idiom, close is not about the door"),
        VoiceEvalCase(
            "did you remember to close the door when you left",
            VoiceIntent.UNKNOWN,
            false,
            "smalltalk",
            "question about past action",
        ),
        VoiceEvalCase("the hardware store is open until nine", VoiceIntent.UNKNOWN, false, "smalltalk", "open refers to store hours"),
        VoiceEvalCase(
            "i think the neighbors garage has been open all day",
            VoiceIntent.UNKNOWN,
            false,
            "smalltalk",
            "observation about neighbor, no command",
        ),
        VoiceEvalCase("he opened the door and the cat ran out", VoiceIntent.UNKNOWN, false, "smalltalk", "narrative past event"),
        VoiceEvalCase(
            "we should really fix that garage door opener sometime",
            VoiceIntent.UNKNOWN,
            false,
            "smalltalk",
            "vague future maintenance talk",
        ),
        VoiceEvalCase(
            "its so cold with the garage open",
            VoiceIntent.UNKNOWN,
            false,
            "smalltalk",
            "complaint about state, no explicit command",
        ),
        VoiceEvalCase(
            "the door closes on its own after ten minutes",
            VoiceIntent.UNKNOWN,
            false,
            "smalltalk",
            "describing behavior, not requesting",
        ),
        VoiceEvalCase("im keeping an open mind about it", VoiceIntent.UNKNOWN, false, "smalltalk", "idiom, open unrelated to door"),
        VoiceEvalCase(
            "they close the pool for the season next week",
            VoiceIntent.UNKNOWN,
            false,
            "smalltalk",
            "close refers to pool schedule",
        ),
        VoiceEvalCase(
            "looks like the garage door finally closed",
            VoiceIntent.UNKNOWN,
            false,
            "smalltalk",
            "observation of completed action",
        ),
        VoiceEvalCase(
            "dont worry i closed it before we drove off",
            VoiceIntent.UNKNOWN,
            false,
            "smalltalk",
            "reassurance about past action",
        ),
        // --- indirect ---
        VoiceEvalCase(
            "close the garage when i leave",
            VoiceIntent.CLOSE,
            false,
            "indirect",
            "Temporal condition defers execution; not a request to move the door now",
        ),
        VoiceEvalCase(
            "im heading out open the garage",
            VoiceIntent.OPEN,
            true,
            "indirect",
            "Context preamble plus explicit unconditional present-tense open command",
        ),
        VoiceEvalCase(
            "open the door and turn off the lights",
            VoiceIntent.OPEN,
            true,
            "indirect",
            "Compound but the door clause is explicit and unconditional",
        ),
        VoiceEvalCase(
            "after dinner close the door",
            VoiceIntent.CLOSE,
            false,
            "indirect",
            "Temporal deferral (after dinner) blocks immediate actuation",
        ),
        VoiceEvalCase(
            "if it starts raining close the garage",
            VoiceIntent.CLOSE,
            false,
            "indirect",
            "Conditional on weather; not an unconditional command",
        ),
        VoiceEvalCase(
            "turn on the lights and close the garage door",
            VoiceIntent.CLOSE,
            true,
            "indirect",
            "Compound with explicit unconditional close clause",
        ),
        VoiceEvalCase(
            "open the garage im pulling in now",
            VoiceIntent.OPEN,
            true,
            "indirect",
            "Explicit present-tense open plus benign context clause",
        ),
        VoiceEvalCase(
            "once the car is out close the door",
            VoiceIntent.CLOSE,
            false,
            "indirect",
            "Deferred until a future condition; not actionable now",
        ),
        VoiceEvalCase(
            "can you close the garage before you go to bed",
            VoiceIntent.CLOSE,
            false,
            "indirect",
            "Permission form plus temporal deferral; both block actionability",
        ),
        VoiceEvalCase(
            "close the door then lock the side gate",
            VoiceIntent.CLOSE,
            true,
            "indirect",
            "Compound sequence; door clause itself is explicit and immediate",
        ),
        VoiceEvalCase(
            "when the delivery guy leaves open it back up",
            VoiceIntent.UNKNOWN,
            false,
            "indirect",
            "Conditional on future event; direction clear but deferred",
        ),
        VoiceEvalCase(
            "remind me to close the garage tonight",
            VoiceIntent.UNKNOWN,
            false,
            "indirect",
            "Reminder request, not a door-movement command",
        ),
        VoiceEvalCase(
            "dont close the garage yet im still loading the car",
            VoiceIntent.UNKNOWN,
            false,
            "indirect",
            "Negation cancels action; no movement requested",
        ),
        VoiceEvalCase(
            "i want the garage open when i get home",
            VoiceIntent.OPEN,
            false,
            "indirect",
            "Desire plus future condition, not a present command; direction as desired state not request",
        ),
        VoiceEvalCase(
            "open the garage unless its already open",
            VoiceIntent.OPEN,
            false,
            "indirect",
            "Conditional clause (unless) makes execution state-dependent, not unconditional",
        ),
    )
}
