/*
 * Copyright 2024 Chris Cartland. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.chriscartland.garage.usecase

/**
 * Button ack tokens the client sends with each remote button push.
 *
 * The token is generated by the client so the server can acknowledge the
 * push with idempotency — the client can retry the same token and the
 * server will only process it once. The app version is included so
 * server logs can correlate button activity with client versions.
 */
object ButtonAckToken {
    fun create(
        currentTimeMillis: Long,
        appVersion: String,
    ): String {
        val buttonAckTokenData = "android-$appVersion-$currentTimeMillis"
        val re = Regex("[^a-zA-Z0-9-_.]")
        return re.replace(buttonAckTokenData, ".")
    }
}
