#!/usr/bin/env python3
"""Generate the UI gallery data file from its declarative manifest.

Reads  MobileGarage/ui-gallery/manifest.yaml   (hand-curated, source of truth)
Writes MobileGarage/ui-gallery/manifest.js     (committed, loaded by index.html)

Why a generated .js file: index.html is opened via file:// where fetch() of
local files is blocked, but <script src="manifest.js"> works. The generator
also does everything a browser can't: resolves `*` globs (AGP reference PNGs
carry content hashes in their filenames that change when previews change),
verifies every referenced image exists, and embeds pixel dimensions so the
viewer can reserve layout space before images load (stable scroll restore).

Manifest schema — see MobileGarage/ui-gallery/README.md. Image value idioms:
  android: ${ref}/Foo_{theme}_*.png     -> {theme} expands per theme (Light/Dark)
  ios:     {light: ${ios}/Bar.1.png}    -> explicit themes only (iOS is light-only)
  wear:    ${wear}/wear-baz.png         -> plain string = all themes (single-theme UI)

Usage:
  python3 scripts/generate-ui-gallery.py           # regenerate manifest.js
  python3 scripts/generate-ui-gallery.py --check   # verify committed file is current
"""

import argparse
import glob
import json
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("ERROR: PyYAML is required (python3 -m pip install pyyaml)")

try:
    from PIL import Image
except ImportError:
    sys.exit("ERROR: Pillow is required (python3 -m pip install pillow)")

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GALLERY_DIR = os.path.join(REPO_ROOT, "MobileGarage", "ui-gallery")
MANIFEST_YAML = os.path.join(GALLERY_DIR, "manifest.yaml")
MANIFEST_JS = os.path.join(GALLERY_DIR, "manifest.js")

HEADER = (
    "// GENERATED by scripts/generate-ui-gallery.py from manifest.yaml — do not edit.\n"
    "// Regenerate after editing manifest.yaml or after screenshot refreshes change\n"
    "// the hashed reference filenames that the manifest's globs resolve to.\n"
)

errors = []


def fail(msg):
    errors.append(msg)


def checked_id(value, context):
    """Reject YAML 1.1 boolean surprises: bare off/on/yes/no parse as booleans."""
    if not isinstance(value, str):
        fail(
            f"{context}: id {value!r} is {type(value).__name__}, not a string — "
            "quote YAML boolean-like ids ('off', 'on', 'yes', 'no')"
        )
        return str(value)
    return value


def apply_aliases(path, aliases):
    for name, value in aliases.items():
        path = path.replace("${" + name + "}", value)
    return path


def resolve_image(path_pattern, context):
    """Resolve one repo-root-relative path (glob allowed) to exactly one file."""
    abs_pattern = os.path.join(REPO_ROOT, path_pattern)
    if any(ch in path_pattern for ch in "*?["):
        matches = sorted(glob.glob(abs_pattern))
        if len(matches) == 0:
            fail(f"{context}: no file matches glob {path_pattern}")
            return None
        if len(matches) > 1:
            rels = [os.path.relpath(m, REPO_ROOT) for m in matches]
            fail(f"{context}: glob {path_pattern} matches {len(matches)} files: {rels}")
            return None
        return matches[0]
    if not os.path.isfile(abs_pattern):
        fail(f"{context}: file not found: {path_pattern}")
        return None
    return abs_pattern


def expand_platform_images(value, themes, theme_tokens, aliases, context):
    """Normalize one platform's image declaration to {theme: path_pattern}."""
    if isinstance(value, str):
        value = apply_aliases(value, aliases)
        if "{theme}" in value:
            return {t: value.replace("{theme}", theme_tokens[t]) for t in themes}
        return {t: value for t in themes}  # single-theme UI: same capture for all
    if isinstance(value, dict):
        out = {}
        for theme, path in value.items():
            if theme not in themes:
                fail(f"{context}: unknown theme key '{theme}' (themes: {themes})")
                continue
            out[theme] = apply_aliases(path, aliases)
        return out
    fail(f"{context}: image value must be a string or a theme map, got {type(value).__name__}")
    return {}


def load_dimensions(abs_path):
    with Image.open(abs_path) as img:
        return img.size


def normalize_items(row, row_ctx, platforms, themes, theme_tokens, aliases):
    """Return (variants, items) in normalized form; record errors via fail()."""
    variants = row.get("variants")
    if variants:
        norm_variants = []
        for v in variants:
            if isinstance(v, str):
                vid = checked_id(v, f"{row_ctx} variant")
                norm_variants.append({"id": vid, "label": vid.replace("-", " ").capitalize()})
            else:
                vid = checked_id(v.get("id"), f"{row_ctx} variant")
                norm_variants.append({"id": vid, "label": v.get("label", vid)})
    else:
        norm_variants = [{"id": "default", "label": "Default"}]
    variant_ids = [v["id"] for v in norm_variants]
    if len(set(variant_ids)) != len(variant_ids):
        fail(f"{row_ctx}: duplicate variant ids")

    norm_items = []
    dim_cache = {}
    for item in row.get("items", []):
        item_ctx = f"{row_ctx} item '{item.get('id', '?')}'"
        images_decl = item.get("images", {})
        # Shorthand: keys that are platform names => single implicit 'default' variant.
        if images_decl and all(k in platforms for k in images_decl):
            images_decl = {"default": images_decl}
        cells = {}
        item_platforms = []
        for variant_id, per_platform in images_decl.items():
            variant_id = checked_id(variant_id, f"{item_ctx} images key")
            if variant_id not in variant_ids:
                fail(f"{item_ctx}: unknown variant '{variant_id}' (declared: {variant_ids})")
                continue
            for platform, value in per_platform.items():
                if platform not in platforms:
                    fail(f"{item_ctx}: unknown platform '{platform}' (declared: {platforms})")
                    continue
                if platform not in item_platforms:
                    item_platforms.append(platform)
                per_theme = expand_platform_images(
                    value, themes, theme_tokens, aliases, f"{item_ctx} [{variant_id}/{platform}]"
                )
                for theme, pattern in per_theme.items():
                    ctx = f"{item_ctx} [{variant_id}/{platform}/{theme}]"
                    abs_path = resolve_image(pattern, ctx)
                    if abs_path is None:
                        continue
                    if abs_path not in dim_cache:
                        dim_cache[abs_path] = load_dimensions(abs_path)
                    width, height = dim_cache[abs_path]
                    cells[f"{variant_id}|{platform}|{theme}"] = {
                        "src": os.path.relpath(abs_path, GALLERY_DIR),
                        "w": width,
                        "h": height,
                    }
        norm_items.append(
            {
                "id": checked_id(item.get("id"), f"{row_ctx} item"),
                "label": item.get("label", item["id"]),
                "platforms": item_platforms,
                "images": cells,
            }
        )
    if not norm_items:
        fail(f"{row_ctx}: no items declared")
    item_ids = [i["id"] for i in norm_items]
    if len(set(item_ids)) != len(item_ids):
        fail(f"{row_ctx}: duplicate item ids")
    return norm_variants, norm_items


def build_manifest(doc):
    platform_labels = doc.get("platformLabels", {})
    platforms = list(platform_labels.keys())
    platform_cycle = doc.get("platformCycle", platforms)
    themes = doc.get("themes", ["light", "dark"])
    theme_tokens = doc.get("themeTokens", {t: t.capitalize() for t in themes})
    aliases = doc.get("pathAliases", {})

    for p in platform_cycle:
        if p not in platforms:
            fail(f"platformCycle entry '{p}' missing from platformLabels")

    sections = []
    row_ids = set()
    for section in doc.get("sections", []):
        rows = []
        for row in section.get("rows", []):
            row_id = row.get("id", "?")
            row_ctx = f"row '{row_id}'"
            if row_id in row_ids:
                fail(f"{row_ctx}: duplicate row id")
            row_ids.add(row_id)
            variants, items = normalize_items(
                row, row_ctx, platforms, themes, theme_tokens, aliases
            )
            rows.append(
                {
                    "id": row_id,
                    "title": row.get("title", row_id),
                    "axis": row.get("axis"),
                    "note": row.get("note"),
                    "height": row.get("height", 360),
                    "maxw": row.get("maxw"),
                    "variants": variants,
                    "items": items,
                }
            )
        sections.append({"title": section.get("title", ""), "rows": rows})

    return {
        "platformCycle": platform_cycle,
        "platformLabels": platform_labels,
        "themes": themes,
        "sections": sections,
    }


def summarize(manifest):
    rows = [r for s in manifest["sections"] for r in s["rows"]]
    cells = [img for r in rows for i in r["items"] for img in i["images"].values()]
    unique_files = {c["src"] for c in cells}
    by_platform = {}
    for r in rows:
        for i in r["items"]:
            for key in i["images"]:
                platform = key.split("|")[1]
                by_platform[platform] = by_platform.get(platform, 0) + 1
    parts = ", ".join(f"{p}: {n}" for p, n in sorted(by_platform.items()))
    print(
        f"ui-gallery: {len(manifest['sections'])} sections, {len(rows)} rows, "
        f"{len(cells)} cells ({parts}), {len(unique_files)} unique images"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed manifest.js matches the manifest.yaml (no write)",
    )
    args = parser.parse_args()

    with open(MANIFEST_YAML, encoding="utf-8") as f:
        doc = yaml.safe_load(f)

    manifest = build_manifest(doc)

    if errors:
        print(f"ui-gallery manifest has {len(errors)} error(s):", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)

    content = HEADER + "window.UI_GALLERY = " + json.dumps(manifest, indent=1) + ";\n"

    if args.check:
        try:
            with open(MANIFEST_JS, encoding="utf-8") as f:
                existing = f.read()
        except FileNotFoundError:
            existing = None
        if existing != content:
            print(
                "ui-gallery: manifest.js is stale — run scripts/generate-ui-gallery.py",
                file=sys.stderr,
            )
            sys.exit(1)
        print("ui-gallery: manifest.js is up to date")
    else:
        with open(MANIFEST_JS, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Wrote {os.path.relpath(MANIFEST_JS, REPO_ROOT)}")
    summarize(manifest)


if __name__ == "__main__":
    main()
