#ifndef GARAGE_CONFIG_H
#define GARAGE_CONFIG_H

#define CONFIG_USE_FAKE_GARAGE_SERVER 1
#define CONFIG_USE_FAKE_GARAGE_HAL 1

#define MAX_DEVICE_ID_LENGTH 256
#define MAX_BUTTON_TOKEN_LENGTH 256

#endif // GARAGE_CONFIG_H
