name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17  # Updated to JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' 
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for release scripts
      working-directory: AndroidGarage
      run: chmod +x release/*.sh
  
    - name: Decrypt secrets
      working-directory: AndroidGarage
      run: ./release/decrypt-secrets.sh
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    - name: Grant execute permission for gradlew
      working-directory: AndroidGarage
      run: chmod +x gradlew
  
    - name: Build Debug
      working-directory: AndroidGarage
      env:  
        SERVER_CONFIG_KEY: ${{ secrets.SERVER_CONFIG_KEY }}
        GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
      run: ./gradlew :app:assembleDebug -PSERVER_CONFIG_KEY="$SERVER_CONFIG_KEY" -PGOOGLE_WEB_CLIENT_ID="$GOOGLE_WEB_CLIENT_ID" 

    - name: Clean secrets
      working-directory: AndroidGarage
      if: always()
      run: ./release/clean-secrets.sh

    - name: Upload build outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-build-outputs
        path: |
          AndroidGarage/app/build/outputs/apk
          AndroidGarage/app/build/outputs/bundle
