name: Android Build and Test CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "internal", "release" ]
    paths:
      - 'AndroidGarage/**'
      - '.github/workflows/android-build-and-test.yml'
  pull_request:
    branches: [ "main", "internal", "release" ]
    paths:
      - 'AndroidGarage/**'
      - '.github/workflows/android-build-and-test.yml'

jobs:
  build_and_test:
    name: Build & Run Android Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for release scripts
      working-directory: AndroidGarage
      run: chmod +x release/*.sh

    - name: Decrypt secrets
      working-directory: AndroidGarage
      run: ./release/decrypt-secrets.sh
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    - name: Grant execute permission for gradlew
      working-directory: AndroidGarage
      run: chmod +x gradlew

    - name: Build Debug
      working-directory: AndroidGarage
      env:
        SERVER_CONFIG_KEY: ${{ secrets.SERVER_CONFIG_KEY }}
        GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
      run: ./gradlew :androidApp:assembleDebug -PSERVER_CONFIG_KEY="$SERVER_CONFIG_KEY" -PGOOGLE_WEB_CLIENT_ID="$GOOGLE_WEB_CLIENT_ID"

    - name: Run Unit Tests
      working-directory: AndroidGarage
      env:
        SERVER_CONFIG_KEY: ${{ secrets.SERVER_CONFIG_KEY }}
        GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
      run: ./gradlew test -PSERVER_CONFIG_KEY="$SERVER_CONFIG_KEY" -PGOOGLE_WEB_CLIENT_ID="$GOOGLE_WEB_CLIENT_ID"

    - name: Clean secrets
      working-directory: AndroidGarage
      if: always()
      run: ./release/clean-secrets.sh

    - name: Upload build and test outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-build-and-test-outputs
        path: |
          AndroidGarage/androidApp/build/outputs/apk
          AndroidGarage/androidApp/build/outputs/bundle
          AndroidGarage/androidApp/build/reports/tests/
          AndroidGarage/androidApp/build/reports/androidTests/

  spotless_check:
    name: Check Code Formatting with Spotless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: AndroidGarage
        run: chmod +x gradlew

      - name: Run Spotless Check
        working-directory: AndroidGarage
        run: ./gradlew spotlessCheck
