name: Android Deploy Internal CI

on:
  push:
    branches: [ "internal" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17' 
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for release scripts
      working-directory: AndroidGarage
      run: chmod +x release/*.sh
  
    - name: Decrypt secrets
      working-directory: AndroidGarage
      run: ./release/decrypt-secrets.sh
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    - name: Grant execute permission for gradlew
      working-directory: AndroidGarage
      run: chmod +x gradlew

    - name: Build AAB
      working-directory: AndroidGarage
      env:  
        SERVER_CONFIG_KEY: ${{ secrets.SERVER_CONFIG_KEY }}
        GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
        GARAGE_RELEASE_KEYSTORE_PWD: ${{ secrets.GARAGE_RELEASE_KEYSTORE_PWD }} 
        GARAGE_RELEASE_KEY_PWD: ${{ secrets.GARAGE_RELEASE_KEY_PWD }} 
      run: ./gradlew :app:bundleRelease -PSERVER_CONFIG_KEY="$SERVER_CONFIG_KEY" -PGOOGLE_WEB_CLIENT_ID="$GOOGLE_WEB_CLIENT_ID" -PGARAGE_RELEASE_KEYSTORE_PWD="$GARAGE_RELEASE_KEYSTORE_PWD" -PGARAGE_RELEASE_KEY_PWD="$GARAGE_RELEASE_KEY_PWD" --stacktrace --debug

    - name: Clean secrets
      working-directory: AndroidGarage
      if: always()
      run: ./release/clean-secrets.sh

    - name: Upload build outputs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-build-outputs
        path: |
          AndroidGarage/app/build/outputs/apk
          AndroidGarage/app/build/outputs/bundle

    - name: Deploy to Google Play
      uses: r0adkll/upload-google-play@v1.0.18
      with:
        serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        packageName: com.chriscartland.garage
        releaseFiles: AndroidGarage/app/build/outputs/bundle/release/*.aab
        track: internal
