name: Deploy Firebase Server

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: FirebaseServer
        run: npm install
      - name: Build
        working-directory: FirebaseServer
        run: npm run build
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIRE"
"BASE_SERVICE_ACCOUNT }}'
      - name: Deploy to Firebase
        run: firebase deploy --only functions --project "${{ secrets.FIREBASE_PROJECT_ID }}"
        working-directory: FirebaseServer
